### ISSUE TITLE
License link in readme is broken. Check casing.

### ISSUE THREAD

**Issue by dcmiddle** [monax/eris-db#539]
In 
https://github.com/monax/eris-db/blob/master/README.md
The license link
https://github.com/monax/eris-db/blob/master/license.md
should be
https://github.com/monax/eris-db/blob/master/LICENSE.md

**Comment by benjaminbollen** [comment]
changed: https://github.com/monax/eris-db/commit/3ac86da5567d3a9bbb2be8affb58a8844b9b1ce7

thanks
