### ISSUE TITLE
eris-db server undefined error

### ISSUE THREAD

**Issue by arunkumarsekar** [monax/eris-db#543]
![issue](https://cloud.githubusercontent.com/assets/2208785/24457898/1b7bef9e-14b5-11e7-8339-6651ebc74b24.png)

This my eris-db instance log., please guide me to resolve this issue..

Thanks

Please include in your bug report:

- [ ] `eris-db version` (docker image tag or branch if built from source)
- [ ] `eris version` (0.12.0)
- [ ] `go version` (if applicable)
- [ ] `docker version` (1.13.1)
- [ ] operating system details (osx/windows/linux)
- [ ] what you expected to happen
- [ ] what actually happened
- [ ] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by benjaminbollen** [comment]
this is erisdb.js; this is a very incomplete bug report; please reopen with more complete information
