### ISSUE TITLE
Map improved /health endpoint from current Status method

### ISSUE THREAD

**Issue by benjaminbollen** [monax/eris-db#548]
- Status() currently gives some indication to the health of the chain, but can be hard to interpret correctly on the receiving side https://github.com/monax/eris-db/blob/master/client/methods/status.go#L30
- define a boolean metric on new endpoint `/health`; possible inputs:
  - last block successfully signed and verified
  - last block received within statistcal window knowing timeouts
  - implicitly, process still running

**Comment by silasdavis** [comment]
For load-balancers, kubernetes, etc I think all we really need is something that will return HTTP status 200 when the node is running. Just so dead nodes can be restarted.

It may want to consider finer-grained notions of health (like whether producing blocks), but it is possible to get this sort off information by subscribing.

Having spoken with Casey the status endpoint supports the kubernetes use case sufficiently so will close this for now.

**Comment by benjaminbollen** [comment]
this way we're not going to have a clean /health endpoint :)
